# Generated by Django 4.1.3 on 2022-12-07 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique Id')),
                ('amenity', models.CharField(help_text='Please enter amenities provided', max_length=255, verbose_name='Amenity')),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['amenity'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('category_name', models.CharField(help_text='Please type a name of the category', max_length=128, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('city_name', models.CharField(help_text='Please enter a name of the city', max_length=50, verbose_name='City')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['city_name', 'country_id'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('country_name', models.CharField(help_text='Enter a name of the country', max_length=50, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique Id')),
                ('currency', models.CharField(help_text='Currency name consisting of 3 letters, eg:EUR/USD/GBP', max_length=3, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['currency'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('hotel_name', models.CharField(help_text='Please enter a name of the Hotel', max_length=100, verbose_name='Hotel Name')),
                ('description', models.TextField(help_text='Please enter a description of the hotel, consisting up to 10000 words.', max_length=10000, verbose_name='Description')),
                ('address', models.CharField(help_text='Address of the hotel', max_length=255, verbose_name='Address')),
                ('price_from', models.IntegerField(verbose_name='Price per night from')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Cover Photo')),
                ('amenities', models.ManyToManyField(help_text='Choose amenities of this room', to='looking_to_stay_app.amenities', verbose_name='amenities')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.city')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['hotel_name'],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pick any name for this album', max_length=255, verbose_name='name')),
                ('hotel_img1', models.ImageField(help_text='Choose the main photo', upload_to='images/')),
                ('hotel_img2', models.ImageField(upload_to='images/')),
                ('hotel_img3', models.ImageField(upload_to='images/')),
                ('hotel_img4', models.ImageField(upload_to='images/')),
                ('hotel_img5', models.ImageField(upload_to='images/')),
                ('hotel_img6', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique Id')),
                ('name', models.CharField(help_text='Name of the room type', max_length=255, verbose_name='Type Name')),
                ('price', models.IntegerField(help_text='Please enter the price for the night', verbose_name='Price Per Night')),
                ('people', models.IntegerField(help_text='Amount of people fit in this room', verbose_name='People')),
                ('currency_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.currency')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique Id')),
                ('room_name', models.CharField(max_length=255, verbose_name='Room name')),
                ('hotel_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.hotel')),
                ('room_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.roomtype')),
            ],
            options={
                'ordering': ['room_name'],
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.hotelimage'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='type_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.currency'),
        ),
        migrations.AddField(
            model_name='city',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.country'),
        ),
    ]
