# Generated by Django 4.1.3 on 2022-11-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(help_text='Please type a name of the category', max_length=128, verbose_name='Category'),
        ),
    ]
