# Generated by Django 4.1.3 on 2022-12-07 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='room_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.roomtype'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
