# Generated by Django 4.1.3 on 2022-11-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0002_alter_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('city_name', models.CharField(help_text='Please enter a name of the city', max_length=50, verbose_name='City')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['city_name', 'country_id'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('company_name', models.CharField(help_text='Please type a name of the company', max_length=128, verbose_name='Company Name')),
                ('email', models.CharField(max_length=128, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Phone Number')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('country_name', models.CharField(help_text='Enter a name of the country', max_length=50, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['country_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('hotel_name', models.CharField(help_text='Please enter a name of the Hotel', max_length=100, verbose_name='Hotel Name')),
                ('description', models.TextField(help_text='Please enter a description of the hotel, consisting up to 10000 words.', max_length=10000, verbose_name='Description')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Cover Photo')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.city')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.company')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['hotel_name', 'company_id'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.country'),
        ),
    ]
