# Generated by Django 4.1.3 on 2022-12-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0002_hotel_room_types_delete_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='room_types',
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_types',
            field=models.ManyToManyField(help_text='Please select room types', to='looking_to_stay_app.roomtype'),
        ),
    ]
