# Generated by Django 4.1.3 on 2022-12-08 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('looking_to_stay_app', '0003_remove_hotel_room_types_hotel_room_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('post_code', models.CharField(max_length=10, verbose_name='Post code')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='check_in')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='check_out')),
                ('special_requests', models.TextField(max_length=10000, verbose_name='Special requests')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['hotel_name']},
        ),
        migrations.AddField(
            model_name='roomtype',
            name='total_rooms',
            field=models.IntegerField(default=0, help_text='Total amount of rooms of this type', verbose_name='Rooms'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique reservation ID', primary_key=True, serialize=False)),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='check_in')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='check_out')),
                ('status', models.CharField(blank=True, choices=[('u', 'Unoccupied'), ('r', 'Reserved'), ('o', 'Occupied')], default='u', help_text='Reservation Status', max_length=1)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.hotel'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='roomtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.roomtype'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
