# Generated by Django 4.1.3 on 2022-12-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0004_alter_hotel_options_remove_hotel_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique Id')),
                ('name', models.CharField(help_text='Name of the room type', max_length=255, verbose_name='Type Name')),
                ('price', models.IntegerField(help_text='Please enter the price for the night', verbose_name='Price Per Night')),
                ('people', models.IntegerField(help_text='Amount of people fit in this room', verbose_name='People')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
