# Generated by Django 4.1.3 on 2022-12-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0004_reservation_alter_hotel_options_roomtype_total_rooms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationstatus',
            options={'ordering': ['reservation'], 'verbose_name': 'Reservation status', 'verbose_name_plural': 'Reservation statuses'},
        ),
        migrations.RemoveField(
            model_name='reservationstatus',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='reservationstatus',
            name='check_out',
        ),
    ]
