# Generated by Django 4.1.3 on 2022-12-02 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0005_roomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique Id')),
                ('currency', models.CharField(help_text='Currency name consisting of 3 letters, eg:EUR/USD/GBP', max_length=3, verbose_name='Currency')),
            ],
            options={
                'ordering': ['currency'],
            },
        ),
        migrations.AddField(
            model_name='roomtype',
            name='currency_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.currency'),
        ),
    ]
