# Generated by Django 4.1.3 on 2022-12-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0006_currency_roomtype_currency_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique Id')),
                ('amenity', models.CharField(help_text='Please enter amenities provided', max_length=255, verbose_name='Amenity')),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['amenity'],
            },
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['currency'], 'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
    ]
