# Generated by Django 4.1.3 on 2022-12-02 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0007_amenities_alter_currency_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unique Id')),
                ('room_name', models.CharField(max_length=255, verbose_name='Room name')),
                ('amenities', models.ManyToManyField(help_text='Choose amenities of this room', to='looking_to_stay_app.amenities', verbose_name='amenities')),
                ('hotel_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.hotel')),
                ('room_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.roomtype')),
            ],
            options={
                'ordering': ['room_name'],
            },
        ),
    ]
