# Generated by Django 4.1.3 on 2022-12-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0008_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price_from',
            field=models.IntegerField(default=0, verbose_name='Price per night from'),
            preserve_default=False,
        ),
    ]
