# Generated by Django 4.1.3 on 2022-12-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0009_hotel_price_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='type_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.currency'),
        ),
    ]
