# Generated by Django 4.1.3 on 2022-12-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0012_remove_image_images_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(default=0, help_text='Address of the hotel', max_length=255, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
