# Generated by Django 4.1.3 on 2022-12-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0013_hotel_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='hotel',
        ),
        migrations.AddField(
            model_name='image',
            name='image2',
            field=models.FileField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
