# Generated by Django 4.1.3 on 2022-12-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0015_hotel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=0, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
