# Generated by Django 4.1.3 on 2022-12-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0017_alter_image_image_alter_image_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
