# Generated by Django 4.1.3 on 2022-12-05 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0018_remove_hotel_images_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pick any name for this album', max_length=255, verbose_name='name')),
                ('hotel_img1', models.ImageField(help_text='Choose the main photo', upload_to='images/')),
                ('hotel_img2', models.ImageField(upload_to='images/')),
                ('hotel_img3', models.ImageField(upload_to='images/')),
                ('hotel_img4', models.ImageField(upload_to='images/')),
                ('hotel_img5', models.ImageField(upload_to='images/')),
                ('hotel_img6', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.hotelimage'),
        ),
    ]
