# Generated by Django 4.1.3 on 2022-12-05 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0020_remove_room_amenities_hotel_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ForeignKey(blank=True, help_text='Choose amenities of this room', null=True, on_delete=django.db.models.deletion.SET_NULL, to='looking_to_stay_app.amenities', verbose_name='amenities'),
        ),
    ]
