# Generated by Django 4.1.3 on 2022-12-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looking_to_stay_app', '0021_remove_hotel_amenities_hotel_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(help_text='Choose amenities of this room', to='looking_to_stay_app.amenities', verbose_name='amenities'),
        ),
    ]
